# This is basic build to run the maven command on push
name: Maven CI/CD

on:
  push:
    branches: [ master ]

jobs: 
  build_and_test:

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK
       uses: actions/setup-java@v1
       with: 
         java-version: 14
     - name: Run Build with Maven
       run: mvn clean install -Dskip test
